# Generated by Django 5.2.7 on 2025-11-05 13:25

from django.db import migrations


def forwards_func(apps, schema_editor):
    # modèles d'origine
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    OldLetting = apps.get_model("oc_lettings_site", "Letting")

    # nouveaux modèles
    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")

    # correspondance anciennes → nouvelles adresses
    old_to_new_addr = {}

    for old in OldAddress.objects.all():
        new = NewAddress.objects.create(
            number=old.number,
            street=old.street,
            city=old.city,
            state=old.state,
            zip_code=old.zip_code,
            country_iso_code=old.country_iso_code,
        )
        old_to_new_addr[old.pk] = new

    for old in OldLetting.objects.all():
        NewLetting.objects.create(
            title=old.title,
            address=old_to_new_addr.get(old.address_id),
        )


def reverse_func(apps, schema_editor):
    NewLetting = apps.get_model("lettings", "Letting")
    NewAddress = apps.get_model("lettings", "Address")
    NewLetting.objects.all().delete()
    NewAddress.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
