# Generated by Django 5.2.7 on 2025-11-05 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("lettings", "0002_copy_data_from_oc_lettings_site"),
        ("profiles", "0002_copy_data_from_oc_lettings_site"),
    ]

    operations = [
        migrations.DeleteModel(name="Letting"),
        migrations.DeleteModel(name="Address"),
        migrations.DeleteModel(name="Profile"),
    ]
